// client/src/components/App.vue
<!-- src/components/App.vue -->
<template>
  <div>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
      <div class="mdl-layout__header-row">
        <div>
        <!-- Title -->
        <a class="mdl-layout-title" v-link="'home'"><img id="veto-logo" src="../assets/images/veto-logo.png" /></a>
        </div>
        <!-- Add spacer, to align navigation to the right -->
        <div>
          <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right">
            <label class="mdl-button mdl-js-button mdl-button--icon"
                  for="fixed-header-drawer-exp">
              <i class="material-icons">search</i>
            </label>
            <div class="mdl-textfield__expandable-holder">
              <input class="mdl-textfield__input" type="text" name="sample"
                    id="fixed-header-drawer-exp">
            </div>
          </div>
        </div>
        <!-- Navigation -->
        <div>
        <nav class="mdl-navigation">
          <a id="show-dialog" class="mdl-navigation__link" href="#" v-on:click="openDialog()"><i class="material-icons">forum</i>Zitiere</a>
          <a class="mdl-navigation__link" @click="quote()" id="show-dialog"><i class="material-icons">forum</i>Zitiere</a>
          <a class="mdl-navigation__link" v-if="user.authenticated" v-link="'login'" @click="logout()">Logout</a>
        </nav>
        </div>
      </div>
    </header>
    </div>
    <div class="mdl-grid">
      <div class="mdl-cell mdl-cell--2-col">Left Column</div>

      <main class="mdl-layout__content mdl-cell mdl-cell--4-col">
        <router-view></router-view>
      </main>

      <div class="mdl-cell mdl-cell--2-col">Right Column</div>
    </div>

    <dialog class="mdl-dialog">
      <h4 class="mdl-dialog__title">Allow data collection?</h4>
      <div class="mdl-dialog__content">
        <p>
          Allowing us to collect data will let us get you the information you want faster.
        </p>
      </div>
      <div class="mdl-dialog__actions">
        <button type="button" class="mdl-button">Agree</button>
        <button type="button" class="mdl-button close">Disagree</button>
      </div>
    </dialog>
  </div>

</template>

<script>
export default {
  data() {
    return {
      user: ""
    }
  },
  methods: {
    logout() {
    }, 
    openDialog() {
        var dialog = document.querySelector('dialog');
        var showDialogButton = document.querySelector('#show-dialog');
        if (! dialog.showModal) {
          dialogPolyfill.registerDialog(dialog);
        }
        showDialogButton.addEventListener('click', function() {
          dialog.showModal();
        });
        dialog.querySelector('.close').addEventListener('click', function() {
          dialog.close();
        });
      }
  }
}
</script>

// client/src/app/app.component.ts
import { Component, Inject } from '@angular/core';
import { MatDialog, MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  
  constructor(public dialog: MatDialog) {}

  createNewQuote() {
    let dialogRef = this.dialog.open(QuotesDialog, {
      width: '250px',
      data: {  }
    });

    dialogRef.afterClosed().subscribe(result => {
      console.log('The dialog was closed');
    });
  }
}

@Component({
  selector: 'quote-dialog',
  templateUrl: './components/home/quote-dialog.html',
})
export class QuotesDialog {

  constructor(
    public dialogRef: MatDialogRef<QuotesDialog>,
    @Inject(MAT_DIALOG_DATA) public data: any
  ) { }

  onNoClick(): void {
    this.dialogRef.close();
  }

}
<!--The content below is only a placeholder and can be replaced.-->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <div>
        <!-- Title -->
        <a class="mdl-layout-title" v-link="'home'">
          <img id="veto-logo" src="../assets/images/veto-logo.png" />
        </a>
      </div>
      <!-- Add spacer, to align navigation to the right -->
      <div>
        <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
              mdl-textfield--floating-label mdl-textfield--align-right">
          <label class="mdl-button mdl-js-button mdl-button--icon" for="fixed-header-drawer-exp">
            <i class="material-icons">search</i>
          </label>
          <div class="mdl-textfield__expandable-holder">
            <input class="mdl-textfield__input" type="text" name="sample" id="fixed-header-drawer-exp">
          </div>
        </div>
      </div>
      <!-- Navigation -->
      <div>
        <nav class="mdl-navigation">
          <a class="mdl-navigation__link" click="quote()" id="show-dialog">
            <i class="material-icons">forum</i>Zitiere</a>
          <a class="mdl-navigation__link" v-if="user.authenticated" v-link="'login'" click="logout()">Logout</a>
        </nav>
      </div>
    </div>
  </header>
</div>
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--2-col">Left Column</div>

  <main class="mdl-layout__content mdl-cell mdl-cell--4-col">
    <div>
      <div v-for="quote in quotes" class="veto-card-wide mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
          <h2 class="mdl-card__title-text"><!--{{ quote.title }}--></h2>
        </div>
        <div>
          <div class="veto-description-controls">
            Vote:
            <a href="#" click="upvote()">
              <i class="material-icons ">thumb_up</i>
            </a>
            <!--{{ quote.votes }}-->
            <a href="#" click="downvote()">
              <i class="material-icons">thumb_down</i>
            </a>
          </div>
          <div class="mdl-card__supporting-text">
            <!--{{ quote.description }}-->
          </div>
          <div>Category</div>
        </div>
        <div class="mdl-card__actions mdl-card--border">
          <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
            Get Started
          </a>
          Save, Comments
        </div>
        <div class="mdl-card__menu">
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
            <i class="material-icons">share</i>
          </button>
        </div>
      </div>

      <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" click="getQuotes()">Get Quotes</button>
    </div>
  </main>

  <div class="mdl-cell mdl-cell--2-col">Right Column</div>
</div>

<router-outlet></router-outlet>
